version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd backend && npm install
      - cd ../frontend && npm install
      
  pre_build:
    commands:
      - echo Running tests...
      - cd backend && npm test || exit 0
      - cd ../frontend && npm test -- --watchAll=false || exit 0
      
  build:
    commands:
      - echo Building the application...
      - cd backend && npm run build || echo "No build script for backend"
      - cd ../frontend && npm run build
      
  post_build:
    commands:
      - echo Creating deployment package...
      - mkdir -p deployment-package
      - cp -r backend/* deployment-package/
      - mkdir -p deployment-package/frontend/build
      - cp -r frontend/build/* deployment-package/frontend/build/
      - cd deployment-package && zip -r ../deployment.zip *
      - echo Deployment package created successfully

artifacts:
  files:
    - deployment.zip
    - appspec.yml
    - scripts/**/*
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'frontend/node_modules/**/*'
