name: Build and Notify

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# This is a minimal workflow that only builds and notifies
# Use the manual deploy.sh script for actual deployment

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci --production

    - name: Run tests (if any)
      working-directory: ./backend
      run: |
        # Add your test commands here
        npm test || echo "No tests configured"

    - name: Build summary
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Frontend built and ready"
        echo "📦 Backend dependencies installed"
        echo ""
        echo "🚀 To deploy manually, run:"
        echo "    ./deploy.sh"
        echo ""
        echo "📖 Or follow the manual deployment guide in docs/deployment.md"

    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Build completed successfully! Ready for manual deployment.'
          })
